# Generated by Django 5.0.6 on 2025-11-17 17:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-fecha', 'hora_inicio']},
        ),
        migrations.AddField(
            model_name='event',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='cupos_totales',
            field=models.PositiveIntegerField(default=0, help_text='0 = sin límite'),
        ),
        migrations.AlterField(
            model_name='event',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='lugar',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='EventAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asistencia a evento',
                'verbose_name_plural': 'Asistencias a eventos',
                'unique_together': {('evento', 'usuario')},
            },
        ),
        migrations.AlterField(
            model_name='event',
            name='asistentes',
            field=models.ManyToManyField(blank=True, related_name='eventos_asistidos', through='events.EventAsistencia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Event_asistentes',
        ),
    ]
