# Generated by Django 5.0.6 on 2025-11-17 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_sync_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventAsistencia',
        ),
    ]
