# Generated by Django 5.0.6 on 2025-11-17 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_delete_eventasistencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-fecha', 'hora_inicio']},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='cupos',
            new_name='cupos_totales',
        ),
        migrations.RemoveField(
            model_name='event',
            name='fin',
        ),
        migrations.RemoveField(
            model_name='event',
            name='inicio',
        ),
        migrations.AddField(
            model_name='event',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='eventos'),
        ),
        migrations.AlterField(
            model_name='event',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='titulo',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='events.event')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
