# Generated by Django 5.0.6 on 2025-11-18 03:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_fix_asistentes_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-fecha', '-hora', 'titulo'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='texto',
            new_name='contenido',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='event',
            new_name='evento',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='hora_fin',
            new_name='hora',
        ),
        migrations.RemoveField(
            model_name='event',
            name='cupos_totales',
        ),
        migrations.RemoveField(
            model_name='event',
            name='hora_inicio',
        ),
        migrations.RemoveField(
            model_name='event',
            name='lugar',
        ),
        migrations.AddField(
            model_name='comentario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='comentario',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='event',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='cupos',
            field=models.PositiveIntegerField(blank=True, help_text='Número máximo de asistentes (opcional).', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='asistentes',
            field=models.ManyToManyField(blank=True, related_name='eventos_inscritos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado'), ('finalizado', 'Finalizado')], default='publicado', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
