# Generated by Django 5.0.6 on 2025-11-29 06:36

import datetime
import django.utils.timezone
import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_comentario_options_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-fecha_inicio', '-hora_inicio'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='cupos',
        ),
        migrations.RemoveField(
            model_name='event',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='event',
            name='hora',
        ),
        migrations.RemoveField(
            model_name='event',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='event',
            name='cupos_totales',
            field=models.PositiveIntegerField(default=0, verbose_name='Cupos totales'),
        ),
        migrations.AddField(
            model_name='event',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='event',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de inicio'),
        ),
        migrations.AddField(
            model_name='event',
            name='fecha_termino',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de término'),
        ),
        migrations.AddField(
            model_name='event',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de inicio'),
        ),
        migrations.AddField(
            model_name='event',
            name='hora_termino',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de término'),
        ),
        migrations.AddField(
            model_name='event',
            name='localidad',
            field=models.CharField(blank=True, max_length=150, verbose_name='Localidad'),
        ),
        migrations.AddField(
            model_name='event',
            name='lugar',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Lugar'),
        ),
        migrations.AlterField(
            model_name='event',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 1, 1, 0, 0)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='event',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'En espera de aprobación'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('finalizado', 'Finalizado')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='event',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=events.models.event_image_upload_to),
        ),
        migrations.AlterField(
            model_name='event',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
