# Generated by Django 5.0.6 on 2025-12-02 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_event_options_alter_event_asistentes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={
                'ordering': ('fecha_inicio', 'hora_inicio', 'titulo'),
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),

        # OJO: NO volvemos a agregar 'hora' ni 'ubicacion' porque ya existen en la BD.

        migrations.AddField(
            model_name='event',
            name='precio_entrada',
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                help_text='Precio de la entrada por persona en pesos chilenos.',
                max_digits=8,
            ),
        ),
        migrations.AddField(
            model_name='event',
            name='solo_mayores_18',
            field=models.BooleanField(
                default=True,
                help_text='Si está marcado, solo pueden asistir personas mayores de 18 años.',
            ),
        ),

        migrations.AlterField(
            model_name='event',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='creado_por',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='eventos_creados',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='event',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='direccion',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='estado',
            field=models.CharField(
                choices=[
                    ('pendiente', 'Pendiente de aprobación'),
                    ('aprobado', 'Aprobado'),
                    ('rechazado', 'Rechazado'),
                ],
                default='pendiente',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='event',
            name='localidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='lugar',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
