# Generated by Django 5.0.6 on 2025-11-15 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('moderador', 'Moderador'), ('vecino', 'Vecino')], default='vecino', help_text='Rol del usuario en la plataforma.', max_length=20),
        ),
    ]
