# Generated by Django 5.0.6 on 2025-11-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('vecino', 'Vecino'), ('moderator', 'Moderador'), ('admin', 'Administrador')], default='vecino', max_length=20),
        ),
    ]
