# Generated by Django 5.0.6 on 2025-11-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('moderator', 'Moderador'), ('neighbor', 'Vecino')], default='neighbor', max_length=20),
        ),
    ]
