# Generated by Django 5.0.6 on 2025-12-03 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, help_text='Usada para validar eventos solo para mayores de 18 años.', null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('vecino', 'Vecino'), ('moderador', 'Moderador'), ('administrador', 'Administrador')], db_column='role', default='vecino', max_length=20),
        ),
    ]
